logging:
  level: debug
  formatter: TXT

api:
  server_host: 0.0.0.0
  server_port: 9092

plugin:
  cloud_provider_type: "aws"
  aws_access_key_id: "put here your Access key ID"
  aws_secret_access_key: "put here your Secret access key"
  aws_region: "put here your aws region"
  check_interval: 30s
  check_timeout: 10s

etcd:
  endpoints:
    - localhost:2379
