// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/plugin.proto

package proto

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	empty "github.com/golang/protobuf/ptypes/empty"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CheckStatus int32

const (
	CheckStatus_UNKNOWN_CHECK_STATUS CheckStatus = 0
	CheckStatus_GREEN                CheckStatus = 1
	CheckStatus_YELLOW               CheckStatus = 2
	CheckStatus_RED                  CheckStatus = 3
)

var CheckStatus_name = map[int32]string{
	0: "UNKNOWN_CHECK_STATUS",
	1: "GREEN",
	2: "YELLOW",
	3: "RED",
}

var CheckStatus_value = map[string]int32{
	"UNKNOWN_CHECK_STATUS": 0,
	"GREEN":                1,
	"YELLOW":               2,
	"RED":                  3,
}

func (x CheckStatus) String() string {
	return proto.EnumName(CheckStatus_name, int32(x))
}

func (CheckStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4368bc2f41172306, []int{0}
}

type CloudProviderType int32

const (
	CloudProviderType_UNKNOWN_CLOUD_PROVIDER_TYPE CloudProviderType = 0
	CloudProviderType_AWS                         CloudProviderType = 1
	CloudProviderType_DO                          CloudProviderType = 2
)

var CloudProviderType_name = map[int32]string{
	0: "UNKNOWN_CLOUD_PROVIDER_TYPE",
	1: "AWS",
	2: "DO",
}

var CloudProviderType_value = map[string]int32{
	"UNKNOWN_CLOUD_PROVIDER_TYPE": 0,
	"AWS":                         1,
	"DO":                          2,
}

func (x CloudProviderType) String() string {
	return proto.EnumName(CloudProviderType_name, int32(x))
}

func (CloudProviderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4368bc2f41172306, []int{1}
}

type PluginInfo struct {
	//unique ID of plugin
	//basically it is slugged URI of plugin repository name e. g. supergiant-underutilized-nodes
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	//plugin version in semver format
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	//short name of plugin
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// detailed plugin description
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PluginInfo) Reset()         { *m = PluginInfo{} }
func (m *PluginInfo) String() string { return proto.CompactTextString(m) }
func (*PluginInfo) ProtoMessage()    {}
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4368bc2f41172306, []int{0}
}

func (m *PluginInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PluginInfo.Unmarshal(m, b)
}
func (m *PluginInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PluginInfo.Marshal(b, m, deterministic)
}
func (m *PluginInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PluginInfo.Merge(m, src)
}
func (m *PluginInfo) XXX_Size() int {
	return xxx_messageInfo_PluginInfo.Size(m)
}
func (m *PluginInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PluginInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PluginInfo proto.InternalMessageInfo

func (m *PluginInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PluginInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *PluginInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PluginInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// plugin instance is running inside k8s cluster, consequently:
// k8s api server doesn't need to be configured and is accessible through k8s service discovery
// AWS credentials need to be configured
type PluginConfig struct {
	ProviderType CloudProviderType `protobuf:"varint,1,opt,name=provider_type,json=providerType,proto3,enum=proto.CloudProviderType" json:"provider_type,omitempty"`
	// Types that are valid to be assigned to CloudProviderConfig:
	//	*PluginConfig_DoConfig
	//	*PluginConfig_AwsConfig
	CloudProviderConfig  isPluginConfig_CloudProviderConfig `protobuf_oneof:"cloud_provider_config"`
	MetricsServerUri     string                             `protobuf:"bytes,5,opt,name=metrics_server_uri,json=metricsServerUri,proto3" json:"metrics_server_uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *PluginConfig) Reset()         { *m = PluginConfig{} }
func (m *PluginConfig) String() string { return proto.CompactTextString(m) }
func (*PluginConfig) ProtoMessage()    {}
func (*PluginConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_4368bc2f41172306, []int{1}
}

func (m *PluginConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PluginConfig.Unmarshal(m, b)
}
func (m *PluginConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PluginConfig.Marshal(b, m, deterministic)
}
func (m *PluginConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PluginConfig.Merge(m, src)
}
func (m *PluginConfig) XXX_Size() int {
	return xxx_messageInfo_PluginConfig.Size(m)
}
func (m *PluginConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_PluginConfig.DiscardUnknown(m)
}

var xxx_messageInfo_PluginConfig proto.InternalMessageInfo

func (m *PluginConfig) GetProviderType() CloudProviderType {
	if m != nil {
		return m.ProviderType
	}
	return CloudProviderType_UNKNOWN_CLOUD_PROVIDER_TYPE
}

type isPluginConfig_CloudProviderConfig interface {
	isPluginConfig_CloudProviderConfig()
}

type PluginConfig_DoConfig struct {
	DoConfig *DoConfig `protobuf:"bytes,2,opt,name=do_config,json=doConfig,proto3,oneof"`
}

type PluginConfig_AwsConfig struct {
	AwsConfig *AwsConfig `protobuf:"bytes,3,opt,name=aws_config,json=awsConfig,proto3,oneof"`
}

func (*PluginConfig_DoConfig) isPluginConfig_CloudProviderConfig() {}

func (*PluginConfig_AwsConfig) isPluginConfig_CloudProviderConfig() {}

func (m *PluginConfig) GetCloudProviderConfig() isPluginConfig_CloudProviderConfig {
	if m != nil {
		return m.CloudProviderConfig
	}
	return nil
}

func (m *PluginConfig) GetDoConfig() *DoConfig {
	if x, ok := m.GetCloudProviderConfig().(*PluginConfig_DoConfig); ok {
		return x.DoConfig
	}
	return nil
}

func (m *PluginConfig) GetAwsConfig() *AwsConfig {
	if x, ok := m.GetCloudProviderConfig().(*PluginConfig_AwsConfig); ok {
		return x.AwsConfig
	}
	return nil
}

func (m *PluginConfig) GetMetricsServerUri() string {
	if m != nil {
		return m.MetricsServerUri
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*PluginConfig) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _PluginConfig_OneofMarshaler, _PluginConfig_OneofUnmarshaler, _PluginConfig_OneofSizer, []interface{}{
		(*PluginConfig_DoConfig)(nil),
		(*PluginConfig_AwsConfig)(nil),
	}
}

func _PluginConfig_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*PluginConfig)
	// cloud_provider_config
	switch x := m.CloudProviderConfig.(type) {
	case *PluginConfig_DoConfig:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DoConfig); err != nil {
			return err
		}
	case *PluginConfig_AwsConfig:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AwsConfig); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("PluginConfig.CloudProviderConfig has unexpected type %T", x)
	}
	return nil
}

func _PluginConfig_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*PluginConfig)
	switch tag {
	case 2: // cloud_provider_config.do_config
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DoConfig)
		err := b.DecodeMessage(msg)
		m.CloudProviderConfig = &PluginConfig_DoConfig{msg}
		return true, err
	case 3: // cloud_provider_config.aws_config
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(AwsConfig)
		err := b.DecodeMessage(msg)
		m.CloudProviderConfig = &PluginConfig_AwsConfig{msg}
		return true, err
	default:
		return false, nil
	}
}

func _PluginConfig_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*PluginConfig)
	// cloud_provider_config
	switch x := m.CloudProviderConfig.(type) {
	case *PluginConfig_DoConfig:
		s := proto.Size(x.DoConfig)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PluginConfig_AwsConfig:
		s := proto.Size(x.AwsConfig)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Stop struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stop) Reset()         { *m = Stop{} }
func (m *Stop) String() string { return proto.CompactTextString(m) }
func (*Stop) ProtoMessage()    {}
func (*Stop) Descriptor() ([]byte, []int) {
	return fileDescriptor_4368bc2f41172306, []int{2}
}

func (m *Stop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stop.Unmarshal(m, b)
}
func (m *Stop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stop.Marshal(b, m, deterministic)
}
func (m *Stop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stop.Merge(m, src)
}
func (m *Stop) XXX_Size() int {
	return xxx_messageInfo_Stop.Size(m)
}
func (m *Stop) XXX_DiscardUnknown() {
	xxx_messageInfo_Stop.DiscardUnknown(m)
}

var xxx_messageInfo_Stop proto.InternalMessageInfo

type Stop_Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stop_Request) Reset()         { *m = Stop_Request{} }
func (m *Stop_Request) String() string { return proto.CompactTextString(m) }
func (*Stop_Request) ProtoMessage()    {}
func (*Stop_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_4368bc2f41172306, []int{2, 0}
}

func (m *Stop_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stop_Request.Unmarshal(m, b)
}
func (m *Stop_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stop_Request.Marshal(b, m, deterministic)
}
func (m *Stop_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stop_Request.Merge(m, src)
}
func (m *Stop_Request) XXX_Size() int {
	return xxx_messageInfo_Stop_Request.Size(m)
}
func (m *Stop_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Stop_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Stop_Request proto.InternalMessageInfo

type Stop_Response struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stop_Response) Reset()         { *m = Stop_Response{} }
func (m *Stop_Response) String() string { return proto.CompactTextString(m) }
func (*Stop_Response) ProtoMessage()    {}
func (*Stop_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_4368bc2f41172306, []int{2, 1}
}

func (m *Stop_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stop_Response.Unmarshal(m, b)
}
func (m *Stop_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stop_Response.Marshal(b, m, deterministic)
}
func (m *Stop_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stop_Response.Merge(m, src)
}
func (m *Stop_Response) XXX_Size() int {
	return xxx_messageInfo_Stop_Response.Size(m)
}
func (m *Stop_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Stop_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Stop_Response proto.InternalMessageInfo

func (m *Stop_Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type CheckRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckRequest) Reset()         { *m = CheckRequest{} }
func (m *CheckRequest) String() string { return proto.CompactTextString(m) }
func (*CheckRequest) ProtoMessage()    {}
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4368bc2f41172306, []int{3}
}

func (m *CheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckRequest.Unmarshal(m, b)
}
func (m *CheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckRequest.Marshal(b, m, deterministic)
}
func (m *CheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckRequest.Merge(m, src)
}
func (m *CheckRequest) XXX_Size() int {
	return xxx_messageInfo_CheckRequest.Size(m)
}
func (m *CheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckRequest proto.InternalMessageInfo

type CheckResponse struct {
	Result               *CheckResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error                string       `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CheckResponse) Reset()         { *m = CheckResponse{} }
func (m *CheckResponse) String() string { return proto.CompactTextString(m) }
func (*CheckResponse) ProtoMessage()    {}
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4368bc2f41172306, []int{4}
}

func (m *CheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckResponse.Unmarshal(m, b)
}
func (m *CheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckResponse.Marshal(b, m, deterministic)
}
func (m *CheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckResponse.Merge(m, src)
}
func (m *CheckResponse) XXX_Size() int {
	return xxx_messageInfo_CheckResponse.Size(m)
}
func (m *CheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckResponse proto.InternalMessageInfo

func (m *CheckResponse) GetResult() *CheckResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *CheckResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type CheckResult struct {
	ExecutionStatus string      `protobuf:"bytes,1,opt,name=execution_status,json=executionStatus,proto3" json:"execution_status,omitempty"`
	Status          CheckStatus `protobuf:"varint,2,opt,name=status,proto3,enum=proto.CheckStatus" json:"status,omitempty"`
	Name            string      `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// TODO: temporary solution need to be redesigned.
	Description          *any.Any  `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Actions              []*Action `protobuf:"bytes,5,rep,name=actions,proto3" json:"actions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CheckResult) Reset()         { *m = CheckResult{} }
func (m *CheckResult) String() string { return proto.CompactTextString(m) }
func (*CheckResult) ProtoMessage()    {}
func (*CheckResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_4368bc2f41172306, []int{5}
}

func (m *CheckResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckResult.Unmarshal(m, b)
}
func (m *CheckResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckResult.Marshal(b, m, deterministic)
}
func (m *CheckResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckResult.Merge(m, src)
}
func (m *CheckResult) XXX_Size() int {
	return xxx_messageInfo_CheckResult.Size(m)
}
func (m *CheckResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckResult.DiscardUnknown(m)
}

var xxx_messageInfo_CheckResult proto.InternalMessageInfo

func (m *CheckResult) GetExecutionStatus() string {
	if m != nil {
		return m.ExecutionStatus
	}
	return ""
}

func (m *CheckResult) GetStatus() CheckStatus {
	if m != nil {
		return m.Status
	}
	return CheckStatus_UNKNOWN_CHECK_STATUS
}

func (m *CheckResult) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CheckResult) GetDescription() *any.Any {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *CheckResult) GetActions() []*Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

type Action struct {
	ActionId             string   `protobuf:"bytes,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_4368bc2f41172306, []int{6}
}

func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetActionId() string {
	if m != nil {
		return m.ActionId
	}
	return ""
}

func (m *Action) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type ActionRequest struct {
	ActionId             string   `protobuf:"bytes,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActionRequest) Reset()         { *m = ActionRequest{} }
func (m *ActionRequest) String() string { return proto.CompactTextString(m) }
func (*ActionRequest) ProtoMessage()    {}
func (*ActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4368bc2f41172306, []int{7}
}

func (m *ActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionRequest.Unmarshal(m, b)
}
func (m *ActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionRequest.Marshal(b, m, deterministic)
}
func (m *ActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionRequest.Merge(m, src)
}
func (m *ActionRequest) XXX_Size() int {
	return xxx_messageInfo_ActionRequest.Size(m)
}
func (m *ActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActionRequest proto.InternalMessageInfo

func (m *ActionRequest) GetActionId() string {
	if m != nil {
		return m.ActionId
	}
	return ""
}

type ActionResponse struct {
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActionResponse) Reset()         { *m = ActionResponse{} }
func (m *ActionResponse) String() string { return proto.CompactTextString(m) }
func (*ActionResponse) ProtoMessage()    {}
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4368bc2f41172306, []int{8}
}

func (m *ActionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionResponse.Unmarshal(m, b)
}
func (m *ActionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionResponse.Marshal(b, m, deterministic)
}
func (m *ActionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionResponse.Merge(m, src)
}
func (m *ActionResponse) XXX_Size() int {
	return xxx_messageInfo_ActionResponse.Size(m)
}
func (m *ActionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ActionResponse proto.InternalMessageInfo

func (m *ActionResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type AwsConfig struct {
	AccessKeyId          string   `protobuf:"bytes,1,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	SecretAccessKey      string   `protobuf:"bytes,2,opt,name=secret_access_key,json=secretAccessKey,proto3" json:"secret_access_key,omitempty"`
	Region               string   `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AwsConfig) Reset()         { *m = AwsConfig{} }
func (m *AwsConfig) String() string { return proto.CompactTextString(m) }
func (*AwsConfig) ProtoMessage()    {}
func (*AwsConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_4368bc2f41172306, []int{9}
}

func (m *AwsConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AwsConfig.Unmarshal(m, b)
}
func (m *AwsConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AwsConfig.Marshal(b, m, deterministic)
}
func (m *AwsConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AwsConfig.Merge(m, src)
}
func (m *AwsConfig) XXX_Size() int {
	return xxx_messageInfo_AwsConfig.Size(m)
}
func (m *AwsConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_AwsConfig.DiscardUnknown(m)
}

var xxx_messageInfo_AwsConfig proto.InternalMessageInfo

func (m *AwsConfig) GetAccessKeyId() string {
	if m != nil {
		return m.AccessKeyId
	}
	return ""
}

func (m *AwsConfig) GetSecretAccessKey() string {
	if m != nil {
		return m.SecretAccessKey
	}
	return ""
}

func (m *AwsConfig) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

// not implemented yet
type DoConfig struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoConfig) Reset()         { *m = DoConfig{} }
func (m *DoConfig) String() string { return proto.CompactTextString(m) }
func (*DoConfig) ProtoMessage()    {}
func (*DoConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_4368bc2f41172306, []int{10}
}

func (m *DoConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoConfig.Unmarshal(m, b)
}
func (m *DoConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoConfig.Marshal(b, m, deterministic)
}
func (m *DoConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoConfig.Merge(m, src)
}
func (m *DoConfig) XXX_Size() int {
	return xxx_messageInfo_DoConfig.Size(m)
}
func (m *DoConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_DoConfig.DiscardUnknown(m)
}

var xxx_messageInfo_DoConfig proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("proto.CheckStatus", CheckStatus_name, CheckStatus_value)
	proto.RegisterEnum("proto.CloudProviderType", CloudProviderType_name, CloudProviderType_value)
	proto.RegisterType((*PluginInfo)(nil), "proto.PluginInfo")
	proto.RegisterType((*PluginConfig)(nil), "proto.PluginConfig")
	proto.RegisterType((*Stop)(nil), "proto.Stop")
	proto.RegisterType((*Stop_Request)(nil), "proto.Stop.Request")
	proto.RegisterType((*Stop_Response)(nil), "proto.Stop.Response")
	proto.RegisterType((*CheckRequest)(nil), "proto.CheckRequest")
	proto.RegisterType((*CheckResponse)(nil), "proto.CheckResponse")
	proto.RegisterType((*CheckResult)(nil), "proto.CheckResult")
	proto.RegisterType((*Action)(nil), "proto.Action")
	proto.RegisterType((*ActionRequest)(nil), "proto.ActionRequest")
	proto.RegisterType((*ActionResponse)(nil), "proto.ActionResponse")
	proto.RegisterType((*AwsConfig)(nil), "proto.AwsConfig")
	proto.RegisterType((*DoConfig)(nil), "proto.DoConfig")
}

func init() { proto.RegisterFile("proto/plugin.proto", fileDescriptor_4368bc2f41172306) }

var fileDescriptor_4368bc2f41172306 = []byte{
	// 740 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0x4d, 0x6f, 0xda, 0x4c,
	0x10, 0x0e, 0xe6, 0xd3, 0x43, 0x20, 0xce, 0xbe, 0x24, 0xaf, 0x5f, 0x72, 0x78, 0x91, 0x0f, 0x6d,
	0x8a, 0x22, 0xa2, 0x10, 0xb5, 0xea, 0xa5, 0x07, 0x0a, 0x56, 0x82, 0x12, 0x01, 0x35, 0xd0, 0x28,
	0x27, 0x8b, 0xd8, 0x1b, 0x6a, 0x85, 0x78, 0xdd, 0x5d, 0x3b, 0x29, 0xbf, 0xa3, 0xbf, 0xae, 0xbf,
	0xa4, 0xd7, 0xca, 0xbb, 0x6b, 0x87, 0x8f, 0xb6, 0x27, 0x7b, 0x9e, 0x99, 0x67, 0x66, 0x76, 0xe7,
	0xd9, 0x01, 0x14, 0x50, 0x12, 0x92, 0xd3, 0x60, 0x11, 0xcd, 0x3d, 0xbf, 0xc5, 0x0d, 0x94, 0xe7,
	0x9f, 0xfa, 0x7f, 0x73, 0x42, 0xe6, 0x0b, 0x7c, 0xca, 0xad, 0xbb, 0xe8, 0xfe, 0x74, 0xe6, 0x2f,
	0x45, 0x44, 0xfd, 0x68, 0xd3, 0x85, 0x1f, 0x83, 0x50, 0x3a, 0x8d, 0x05, 0xc0, 0x88, 0xa7, 0xeb,
	0xfb, 0xf7, 0x04, 0x55, 0x41, 0xf1, 0x5c, 0x3d, 0xd3, 0xc8, 0x1c, 0xab, 0x96, 0xe2, 0xb9, 0x48,
	0x87, 0xe2, 0x13, 0xa6, 0xcc, 0x23, 0xbe, 0xae, 0x70, 0x30, 0x31, 0x11, 0x82, 0x9c, 0x3f, 0x7b,
	0xc4, 0x7a, 0x96, 0xc3, 0xfc, 0x1f, 0x35, 0xa0, 0xec, 0x62, 0xe6, 0x50, 0x2f, 0x08, 0x63, 0x46,
	0x8e, 0xbb, 0x56, 0x21, 0xe3, 0x67, 0x06, 0x76, 0x45, 0xb9, 0x2e, 0xf1, 0xef, 0xbd, 0x39, 0xfa,
	0x00, 0x95, 0x80, 0x92, 0x27, 0xcf, 0xc5, 0xd4, 0x0e, 0x97, 0x01, 0xe6, 0xb5, 0xab, 0x6d, 0x5d,
	0x74, 0xd7, 0xea, 0x2e, 0x48, 0xe4, 0x8e, 0x64, 0xc0, 0x64, 0x19, 0x60, 0x6b, 0x37, 0x58, 0xb1,
	0x50, 0x0b, 0x54, 0x97, 0xd8, 0x0e, 0xcf, 0xc5, 0x3b, 0x2c, 0xb7, 0xf7, 0x24, 0xb5, 0x47, 0x44,
	0x89, 0xcb, 0x1d, 0xab, 0xe4, 0xca, 0x7f, 0x74, 0x06, 0x30, 0x7b, 0x66, 0x09, 0x21, 0xcb, 0x09,
	0x9a, 0x24, 0x74, 0x9e, 0x59, 0xca, 0x50, 0x67, 0x89, 0x81, 0x4e, 0x00, 0x3d, 0xe2, 0x90, 0x7a,
	0x0e, 0xb3, 0x19, 0xa6, 0x4f, 0x98, 0xda, 0x11, 0xf5, 0xf4, 0x3c, 0x3f, 0x9b, 0x26, 0x3d, 0x63,
	0xee, 0x98, 0x52, 0xef, 0xe3, 0xbf, 0x70, 0xe0, 0xc4, 0x3d, 0xdb, 0xe9, 0xa9, 0x44, 0x2d, 0xe3,
	0x1c, 0x72, 0xe3, 0x90, 0x04, 0x75, 0x15, 0x8a, 0x16, 0xfe, 0x1a, 0x61, 0x16, 0xd6, 0x1b, 0x50,
	0xb2, 0x30, 0x0b, 0x88, 0xcf, 0x30, 0xaa, 0x41, 0x1e, 0x53, 0x4a, 0xa8, 0xbc, 0x7b, 0x61, 0x18,
	0x55, 0xd8, 0xed, 0x7e, 0xc1, 0xce, 0x83, 0x64, 0x18, 0x9f, 0xa0, 0x22, 0x6d, 0x49, 0x6b, 0x42,
	0x81, 0x62, 0x16, 0x2d, 0x42, 0xce, 0x2b, 0xb7, 0x51, 0x72, 0x6f, 0x32, 0x2a, 0x5a, 0x84, 0x96,
	0x8c, 0x78, 0x29, 0xa1, 0xac, 0x96, 0xf8, 0x91, 0x81, 0xf2, 0x4a, 0x34, 0x7a, 0x03, 0x1a, 0xfe,
	0x86, 0x9d, 0x28, 0x1e, 0x97, 0xcd, 0xc2, 0x59, 0x18, 0x31, 0xd9, 0xd3, 0x5e, 0x8a, 0x8f, 0x39,
	0x1c, 0x17, 0x97, 0x01, 0x0a, 0x1f, 0xda, 0x5a, 0x71, 0x11, 0x63, 0xc9, 0x88, 0xdf, 0xca, 0xe5,
	0xdd, 0xb6, 0x5c, 0xca, 0xed, 0x5a, 0x4b, 0xa8, 0xb5, 0x95, 0xa8, 0xb5, 0xd5, 0xf1, 0x97, 0x6b,
	0x22, 0x42, 0xaf, 0xa1, 0x38, 0x73, 0xe2, 0x3f, 0xa6, 0xe7, 0x1b, 0xd9, 0xe3, 0x72, 0xbb, 0x92,
	0x4c, 0x90, 0xa3, 0x56, 0xe2, 0x35, 0x2e, 0xa0, 0x20, 0x20, 0x74, 0x04, 0xaa, 0x00, 0xed, 0x54,
	0xde, 0x25, 0x01, 0xf4, 0xdd, 0x4d, 0xd9, 0x2a, 0xdb, 0xb2, 0x3d, 0x81, 0x8a, 0xcc, 0x2d, 0x06,
	0xf1, 0xd7, 0x7c, 0xc6, 0x2b, 0xa8, 0x26, 0xd1, 0x9b, 0xd3, 0x5d, 0xbb, 0x7a, 0x06, 0x6a, 0xaa,
	0x39, 0x64, 0x40, 0x65, 0xe6, 0x38, 0x98, 0x31, 0xfb, 0x01, 0x2f, 0x5f, 0xb2, 0x96, 0x05, 0x78,
	0x85, 0x97, 0x7d, 0x17, 0x35, 0x61, 0x9f, 0x61, 0x87, 0xe2, 0xd0, 0x7e, 0x09, 0x95, 0x29, 0xf7,
	0x84, 0xa3, 0x93, 0x44, 0xa3, 0xc3, 0x58, 0x19, 0xf3, 0xf8, 0x3c, 0xe2, 0xca, 0xa5, 0x65, 0x00,
	0x94, 0x92, 0x97, 0xd1, 0xbc, 0x90, 0xa3, 0x97, 0xf3, 0xd4, 0xa1, 0x36, 0x1d, 0x5c, 0x0d, 0x86,
	0x37, 0x03, 0xbb, 0x7b, 0x69, 0x76, 0xaf, 0xec, 0xf1, 0xa4, 0x33, 0x99, 0x8e, 0xb5, 0x1d, 0xa4,
	0x42, 0xfe, 0xc2, 0x32, 0xcd, 0x81, 0x96, 0x41, 0x00, 0x85, 0x5b, 0xf3, 0xfa, 0x7a, 0x78, 0xa3,
	0x29, 0xa8, 0x08, 0x59, 0xcb, 0xec, 0x69, 0xd9, 0xa6, 0x09, 0xfb, 0x5b, 0x2f, 0x15, 0xfd, 0x0f,
	0x47, 0x69, 0xba, 0xeb, 0xe1, 0xb4, 0x67, 0x8f, 0xac, 0xe1, 0xe7, 0x7e, 0xcf, 0xb4, 0xec, 0xc9,
	0xed, 0xc8, 0xd4, 0x76, 0x62, 0x7a, 0xe7, 0x66, 0xac, 0x65, 0x50, 0x01, 0x94, 0xde, 0x50, 0x53,
	0xda, 0xdf, 0x15, 0x28, 0x88, 0xed, 0x80, 0xce, 0x20, 0xc7, 0x17, 0xd2, 0xe1, 0x96, 0x1c, 0xcc,
	0x78, 0x79, 0xd5, 0xf7, 0xe5, 0xc8, 0x57, 0x76, 0x57, 0x1b, 0xf2, 0xfc, 0x34, 0xe8, 0x9f, 0xf5,
	0x47, 0x20, 0x1e, 0x5b, 0x6d, 0xe3, 0x65, 0x88, 0xc1, 0xbc, 0x4d, 0x15, 0x52, 0x5b, 0xd7, 0x90,
	0x64, 0x1d, 0x6c, 0xa0, 0x92, 0xf6, 0x1e, 0x54, 0x71, 0x85, 0x11, 0xc5, 0x69, 0xb9, 0xd5, 0xbd,
	0x56, 0xff, 0x43, 0xdf, 0xf1, 0xb9, 0xe2, 0x35, 0x90, 0x92, 0x62, 0xa3, 0xb5, 0xd9, 0xa3, 0x04,
	0x45, 0xb1, 0xbb, 0x02, 0x07, 0xcf, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0x9f, 0x9f, 0xf0, 0x5d,
	0xfd, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PluginClient is the client API for Plugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PluginClient interface {
	Info(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*PluginInfo, error)
	Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
	Action(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	Configure(ctx context.Context, in *PluginConfig, opts ...grpc.CallOption) (*empty.Empty, error)
	//Graceful Shutdown Plugin
	Stop(ctx context.Context, in *Stop_Request, opts ...grpc.CallOption) (*Stop_Response, error)
}

type pluginClient struct {
	cc *grpc.ClientConn
}

func NewPluginClient(cc *grpc.ClientConn) PluginClient {
	return &pluginClient{cc}
}

func (c *pluginClient) Info(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*PluginInfo, error) {
	out := new(PluginInfo)
	err := c.cc.Invoke(ctx, "/proto.Plugin/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, "/proto.Plugin/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) Action(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, "/proto.Plugin/Action", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) Configure(ctx context.Context, in *PluginConfig, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.Plugin/Configure", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) Stop(ctx context.Context, in *Stop_Request, opts ...grpc.CallOption) (*Stop_Response, error) {
	out := new(Stop_Response)
	err := c.cc.Invoke(ctx, "/proto.Plugin/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServer is the server API for Plugin service.
type PluginServer interface {
	Info(context.Context, *empty.Empty) (*PluginInfo, error)
	Check(context.Context, *CheckRequest) (*CheckResponse, error)
	Action(context.Context, *ActionRequest) (*ActionResponse, error)
	Configure(context.Context, *PluginConfig) (*empty.Empty, error)
	//Graceful Shutdown Plugin
	Stop(context.Context, *Stop_Request) (*Stop_Response, error)
}

func RegisterPluginServer(s *grpc.Server, srv PluginServer) {
	s.RegisterService(&_Plugin_serviceDesc, srv)
}

func _Plugin_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Plugin/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Info(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Plugin/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Check(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_Action_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Action(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Plugin/Action",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Action(ctx, req.(*ActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Plugin/Configure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Configure(ctx, req.(*PluginConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Stop_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Plugin/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Stop(ctx, req.(*Stop_Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Plugin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Plugin",
	HandlerType: (*PluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _Plugin_Info_Handler,
		},
		{
			MethodName: "Check",
			Handler:    _Plugin_Check_Handler,
		},
		{
			MethodName: "Action",
			Handler:    _Plugin_Action_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _Plugin_Configure_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Plugin_Stop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/plugin.proto",
}
